### ISSUE TITLE
install problem on Kali - syntax issue

### ISSUE THREAD

**Issue by williamcaput** [libcrack/iker#1]
root@extsec:~/iker# ./setup.py install
running install
running bdist_egg
running egg_info
writing requirements to iker.egg-info/requires.txt
writing iker.egg-info/PKG-INFO
writing top-level names to iker.egg-info/top_level.txt
writing dependency_links to iker.egg-info/dependency_links.txt
writing entry points to iker.egg-info/entry_points.txt
reading manifest file 'iker.egg-info/SOURCES.txt'
writing manifest file 'iker.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/iker
copying build/lib.linux-x86_64-2.7/iker/ike_scan_wrapper.py -> build/bdist.linux-x86_64/egg/iker
copying build/lib.linux-x86_64-2.7/iker/color.py -> build/bdist.linux-x86_64/egg/iker
copying build/lib.linux-x86_64-2.7/iker/logger.py -> build/bdist.linux-x86_64/egg/iker
copying build/lib.linux-x86_64-2.7/iker/**init**.py -> build/bdist.linux-x86_64/egg/iker
copying build/lib.linux-x86_64-2.7/iker/iker.py -> build/bdist.linux-x86_64/egg/iker
byte-compiling build/bdist.linux-x86_64/egg/iker/ike_scan_wrapper.py to ike_scan_wrapper.pyc
  File "build/bdist.linux-x86_64/egg/iker/ike_scan_wrapper.py", line 97
    def self.execve(command):
            ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/iker/color.py to color.pyc
byte-compiling build/bdist.linux-x86_64/egg/iker/logger.py to logger.pyc
byte-compiling build/bdist.linux-x86_64/egg/iker/**init**.py to **init**.pyc
byte-compiling build/bdist.linux-x86_64/egg/iker/iker.py to iker.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying iker.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying iker.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying iker.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying iker.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying iker.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying iker.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/iker-2.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing iker-2.1-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/iker-2.1-py2.7.egg
Copying iker-2.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
iker 2.1 is already the active version in easy-install.pth
Installing iker script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/iker-2.1-py2.7.egg
Processing dependencies for iker==2.1
Searching for progressbar==2.3
Best match: progressbar 2.3
Processing progressbar-2.3-py2.7.egg
progressbar 2.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/progressbar-2.3-py2.7.egg
Finished processing dependencies for iker==2.1

root@extsec:~/iker# iker
Traceback (most recent call last):
  File "/usr/local/bin/iker", line 9, in <module>
    load_entry_point('iker==2.1', 'console_scripts', 'iker')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "build/bdist.linux-x86_64/egg/iker/iker.py", line 12, in <module>
  File "/usr/local/lib/python2.7/dist-packages/iker-2.1-py2.7.egg/iker/ike_scan_wrapper.py", line 97
    def self.execve(command):
            ^
SyntaxError: invalid syntax

**Comment by libcrack** [comment]
Development branch is unsupported. Feel free to fix && commit :-)
